title: Libera Chat
description: A next-generation IRC network for FOSS projects collaboration!
baseurl: ""
url: https://libera.chat

twitter:
  username: liberachat
  card: summary
facebook:
  publisher: liberachat
irc:
  plaintext:
    name: irc.libera.chat:6667 (plaintext)
    link: irc://irc.libera.chat:6667
  tls:
    name: irc.libera.chat:6697 (TLS)
    link: ircs://irc.libera.chat:6697

collections_dir: content

collections:
  guides:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: guides

locale: en_GB

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
